### PR TITLE
Update README with project plan

### PR DESCRIPTION
**Pull request by SaurusXI**

### CODE REVIEW

**Comment by L04DB4L4NC3R** [comment]
Take a pull from the template repo

**Comment by SaurusXI** [comment]
@L04DB4L4NC3R done, take a look

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R done, take a look

Works. Improve your commit messages from the next time

**Comment by L04DB4L4NC3R** [comment]
@SaurusXI open a new PR for adding this aftyer the UI badge:

```
[![Join Us](https://img.shields.io/badge/Join%20Us-Developer%20Student%20Clubs-red)](https://dsc.community.dev/vellore-institute-of-technology/)
```

**Pull request merged**
